.github

diff --git a/.github/workflows/liquibase-status-spanner.yml b/.github/workflows/liquibase-status-spanner.yml
--- a/.github/workflows/liquibase-status-spanner.yml
+++ b/.github/workflows/liquibase-status-spanner.yml
@@ -13,6 +13,9 @@ on:
         required: true
 
 env:
+
+
+name: Liquibase Status with Spanneron:  workflow_dispatch:    inputs:      app_env:        description: 'Environment (dev, stage, prod-c)'        default: 'dev'        required: true      spanner_instance:        description: 'Spanner instance (e.g., demo, b2b-dev01)'        default: $0
   CHANGE_LOG_FILE: sql/changelog-root.xml
   JDBC_URL: jdbc:cloudspanner:/projects/${{ vars.GCP_PROJECT_ID }}/instances/${{ inputs.spanner_instance }}/databases/demo_liquibase?credentials=${{ github.workspace }}/sa-liquibase.json
   SEARCH_PATH: sql
@@ -79,8 +82,8 @@ jobs:
           echo "Listing all JARs in m2-repository:"
           find ${{ env.WORKSPACE }}/m2-repository -type f -name "*.jar" -ls || echo "No JARs found in m2-repository"
           echo "Checking specific JAR files:"
-          ls -l ${{ env.WORKSPACE }}/m2-repository/com/google/cloud/google-cloud-spanner-jdbc/2.14.1/google-cloud-spanner-jdbc-2.14.1.jar || echo "Spanner JDBC JAR not found"
-          ls -l ${{ env.WORKSPACE }}/m2-repository/com/google/cloud/google-cloud-spanner/6.67.0/google-cloud-spanner-6.67.0.jar || echo "Spanner JAR not found"
+          ls -l ${{ env.WORKSPACE }}/m2-repository/com/google/cloud/google-cloud-spanner-jdbc/2.5.7/google-cloud-spanner-jdbc-2.5.7.jar || echo "Spanner JDBC JAR not found"
+          ls -l ${{ env.WORKSPACE }}/m2-repository/com/google/cloud/google-cloud-spanner/1.50.0/google-cloud-spanner-1.50.0.jar || echo "Spanner JAR not found"
           ls -l ${{ env.WORKSPACE }}/m2-repository/com/google/guava/guava/33.3.0-jre/guava-33.3.0-jre.jar || echo "Guava JAR not found"
           ls -l ${{ env.WORKSPACE }}/m2-repository/com/google/protobuf/protobuf-java/3.25.5/protobuf-java-3.25.5.jar || echo "Protobuf Java JAR not found"
           ls -l ${{ env.WORKSPACE }}/m2-repository/com/google/protobuf/protobuf-java-util/3.25.5/protobuf-java-util-3.25.5.jar || echo "Protobuf Java Util JAR not found"
@@ -107,7 +110,7 @@ jobs:
           url: ${{ env.JDBC_URL }}
           driver: com.google.cloud.spanner.jdbc.JdbcDriver
           searchPath: ${{ env.SEARCH_PATH }}
-          classpath: ${{ env.WORKSPACE }}/m2-repository/com/google/cloud/google-cloud-spanner-jdbc/2.14.1/google-cloud-spanner-jdbc-2.14.1.jar:${{ env.WORKSPACE }}/m2-repository/com/google/cloud/google-cloud-spanner/6.67.0/google-cloud-spanner-6.67.0.jar:${{ env.WORKSPACE }}/m2-repository/com/google/guava/guava/33.3.0-jre/guava-33.3.0-jre.jar:${{ env.WORKSPACE }}/m2-repository/com/google/protobuf/protobuf-java/3.25.5/protobuf-java-3.25.5.jar:${{ env.WORKSPACE }}/m2-repository/com/google/protobuf/protobuf-java-util/3.25.5/protobuf-java-util-3.25.5.jar
+          classpath: ${{ env.WORKSPACE }}/m2-repository/com/google/cloud/google-cloud-spanner-jdbc/2.5.7/google-cloud-spanner-jdbc-2.5.7.jar:${{ env.WORKSPACE }}/m2-repository/com/google/cloud/google-cloud-spanner/1.50.0/google-cloud-spanner-1.50.0.jar:${{ env.WORKSPACE }}/m2-repository/com/google/guava/guava/33.3.0-jre/guava-33.3.0-jre.jar:${{ env.WORKSPACE }}/m2-repository/com/google/protobuf/protobuf-java/3.25.5/protobuf-java-3.25.5.jar:${{ env.WORKSPACE }}/m2-repository/com/google/protobuf/protobuf-java-util/3.25.5/protobuf-java-util-3.25.5.jar
           contextFilter: ${{ inputs.app_env }}
           logLevel: debug
         env:
