.github

diff --git a/.github/workflows/liquibase-status-spanner.yml b/.github/workflows/liquibase-status-spanner.yml
--- a/.github/workflows/liquibase-status-spanner.yml
+++ b/.github/workflows/liquibase-status-spanner.yml
@@ -39,8 +39,8 @@ jobs:
       # Copy Maven repository to workspace
       - name: Copy Maven Repository to Workspace
         run: |
-          mkdir -p /github/workspace/m2-repository
-          cp -r ~/.m2/repository/* /github/workspace/m2-repository/
+          mkdir -p m2-repository
+          cp -r ~/.m2/repository/* m2-repository/
         shell: bash
 
       # Save service account key from secret
@@ -54,10 +54,10 @@ jobs:
         run: |
           echo "JAVA_HOME is set to $JAVA_HOME"
           java -version
-          echo "Checking JAR files in /github/workspace/m2-repository:"
-          ls -l /github/workspace/m2-repository/com/google/cloud/google-cloud-spanner-jdbc/2.5.7/google-cloud-spanner-jdbc-2.5.7.jar || echo "Spanner JDBC JAR not found"
-          ls -l /github/workspace/m2-repository/com/google/cloud/google-cloud-spanner-hibernate-dialect/1.5.0/google-cloud-spanner-hibernate-dialect-1.5.0.jar || echo "Hibernate Dialect JAR not found"
-          ls -l /github/workspace/m2-repository/com/google/cloud/google-cloud-storage/2.7.2/google-cloud-storage-2.7.2.jar || echo "Storage JAR not found"
+          echo "Checking JAR files in m2-repository:"
+          ls -l m2-repository/com/google/cloud/google-cloud-spanner-jdbc/2.5.7/google-cloud-spanner-jdbc-2.5.7.jar || echo "Spanner JDBC JAR not found"
+          ls -l m2-repository/com/google/cloud/google-cloud-spanner-hibernate-dialect/1.5.0/google-cloud-spanner-hibernate-dialect-1.5.0.jar || echo "Hibernate Dialect JAR not found"
+          ls -l m2-repository/com/google/cloud/google-cloud-storage/2.7.2/google-cloud-storage-2.7.2.jar || echo "Storage JAR not found"
         shell: bash
 
       # Run Liquibase Status Action
