few chnaged added

diff --git a/.github/workflows/liquibase-status-spanner.yml b/.github/workflows/liquibase-status-spanner.yml
--- a/.github/workflows/liquibase-status-spanner.yml
+++ b/.github/workflows/liquibase-status-spanner.yml
@@ -20,7 +20,7 @@ env:
   CHANGE_LOG_FILE: sql/changelog-root.xml
   JDBC_URL: jdbc:cloudspanner:/projects/${{ vars.GCP_PROJECT_ID }}/instances/${{ inputs.spanner_instance }}/databases/demo_liquibase
   SEARCH_PATH: /liquibase,/liquibase/sql
-  LIQUIBASE_IMAGE: liquibase:4.29.2  
+  LIQUIBASE_IMAGE: liquibase:4.32.0  
 
 jobs:
   liquibase-update-tag:
@@ -150,13 +150,13 @@ jobs:
             -e GOOGLE_APPLICATION_CREDENTIALS=/liquibase/gcp-creds.json \
             --entrypoint=/bin/sh \
             ${{ env.LIQUIBASE_IMAGE }} \
-            -c "java -jar /liquibase/lib/liquibase-core.jar --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} status --contexts='${{ env.APP_ENV }}' | grep 'is up to date' | wc -l")
+            -c "liquibase --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} --log-level=debug status --contexts='${{ env.APP_ENV }}' | grep 'is up to date' | wc -l")
           echo "UPDATE_STATUS=$UPDATE_STATUS" >> $GITHUB_ENV
           echo "0" > "${{ github.workspace }}/liquibase-status.txt"
           cat "${{ github.workspace }}/liquibase-status.txt"
         shell: bash
         continue-on-error: true
-
+      
       - name: Run Liquibase Commands
         id: run-liquibase-commands
         if: env.SHOULD_RUN == 'true' && env.SQL_CODE_STATUS != '0' && env.UPDATE_STATUS != '1'
@@ -166,19 +166,20 @@ jobs:
             -e GOOGLE_APPLICATION_CREDENTIALS=/liquibase/gcp-creds.json \
             --entrypoint=/bin/sh \
             ${{ env.LIQUIBASE_IMAGE }} \
-            -c "java -jar /liquibase/lib/liquibase-core.jar --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} validate" || { echo "Liquibase validate failed"; exit 1; }
+            -c "liquibase --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} --log-level=debug validate" || { echo "Liquibase validate failed"; exit 1; }
           docker run --rm \
             -v "${{ github.workspace }}:/liquibase" \
             -e GOOGLE_APPLICATION_CREDENTIALS=/liquibase/gcp-creds.json \
             --entrypoint=/bin/sh \
             ${{ env.LIQUIBASE_IMAGE }} \
-            -c "java -jar /liquibase/lib/liquibase-core.jar --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} tag '${{ env.APP_VERSION }}'" || { echo "Liquibase tag failed"; exit 1; }
+            -c "liquibase --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} --log-level=debug tag '${{ env.APP_VERSION }}'" || { echo "Liquibase tag failed"; exit 1; }
           docker run --rm \
             -v "${{ github.workspace }}:/liquibase" \
             -e GOOGLE_APPLICATION_CREDENTIALS=/liquibase/gcp-creds.json \
             --entrypoint=/bin/sh \
             ${{ env.LIQUIBASE_IMAGE }} \
-            -c "java -jar /liquibase/lib/liquibase-core.jar --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} update --contexts='${{ env.APP_ENV }}' && echo \$? > /liquibase/liquibase-status.txt" || { echo "Liquibase update failed"; exit 1; }
+            -c "bash -x -c 'liquibase --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} --log-level=debug update --contexts='\${APP_ENV}' && echo \$? > /liquibase/liquibase-status.txt'" \
+            APP_ENV="${{ env.APP_ENV }}" || { echo "Liquibase update failed"; exit 1; }
           cat "${{ github.workspace }}/liquibase-status.txt"
         shell: bash
 
