few chnaged added

diff --git a/.github/workflows/liquibase-status-spanner.yml b/.github/workflows/liquibase-status-spanner.yml
--- a/.github/workflows/liquibase-status-spanner.yml
+++ b/.github/workflows/liquibase-status-spanner.yml
@@ -20,7 +20,7 @@ env:
   CHANGE_LOG_FILE: sql/changelog-root.xml
   JDBC_URL: jdbc:cloudspanner:/projects/${{ vars.GCP_PROJECT_ID }}/instances/${{ inputs.spanner_instance }}/databases/demo_liquibase
   SEARCH_PATH: /liquibase,/liquibase/sql
-  LIQUIBASE_IMAGE: liquibase/liquibase:4.32.0
+  LIQUIBASE_IMAGE: liquibase:4.32.0  
 
 jobs:
   liquibase-update-tag:
@@ -136,6 +136,11 @@ jobs:
             -c "bash -c 'ls -l /liquibase/liquibase-lib; cat /liquibase/liquibase.properties; ls -l /liquibase/gcp-creds.json; ls -l /liquibase/sql'"
         shell: bash
 
+      - name: Debug Liquibase Executable
+        run: |
+          docker run --rm --entrypoint=/bin/sh ${{ env.LIQUIBASE_IMAGE }} -c "find / -name liquibase 2>/dev/null; ls -l /liquibase; ls -l /usr/local/bin; echo \$PATH"
+        shell: bash
+
       - name: Check Liquibase Status
         id: liquibase-status
         if: env.SHOULD_RUN == 'true' && env.SQL_CODE_STATUS != '0'
@@ -145,7 +150,7 @@ jobs:
             -e GOOGLE_APPLICATION_CREDENTIALS=/liquibase/gcp-creds.json \
             --entrypoint=/bin/sh \
             ${{ env.LIQUIBASE_IMAGE }} \
-            -c "/liquibase/liquibase --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} --log-level=debug status --contexts='${{ env.APP_ENV }}' | grep 'is up to date' | wc -l")
+            -c "PATH=\$PATH:/liquibase:/usr/local/bin /liquibase/liquibase --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} --log-level=debug status --contexts='${{ env.APP_ENV }}' | grep 'is up to date' | wc -l")
           echo "UPDATE_STATUS=$UPDATE_STATUS" >> $GITHUB_ENV
           echo "0" > "${{ github.workspace }}/liquibase-status.txt"
           cat "${{ github.workspace }}/liquibase-status.txt"
@@ -161,19 +166,19 @@ jobs:
             -e GOOGLE_APPLICATION_CREDENTIALS=/liquibase/gcp-creds.json \
             --entrypoint=/bin/sh \
             ${{ env.LIQUIBASE_IMAGE }} \
-            -c "/liquibase/liquibase --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} --log-level=debug validate" || { echo "Liquibase validate failed"; exit 1; }
+            -c "PATH=\$PATH:/liquibase:/usr/local/bin /liquibase/liquibase --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} --log-level=debug validate" || { echo "Liquibase validate failed"; exit 1; }
           docker run --rm \
             -v "${{ github.workspace }}:/liquibase" \
             -e GOOGLE_APPLICATION_CREDENTIALS=/liquibase/gcp-creds.json \
             --entrypoint=/bin/sh \
             ${{ env.LIQUIBASE_IMAGE }} \
-            -c "/liquibase/liquibase --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} --log-level=debug tag '${{ env.APP_VERSION }}'" || { echo "Liquibase tag failed"; exit 1; }
+            -c "PATH=\$PATH:/liquibase:/usr/local/bin /liquibase/liquibase --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} --log-level=debug tag '${{ env.APP_VERSION }}'" || { echo "Liquibase tag failed"; exit 1; }
           docker run --rm \
             -v "${{ github.workspace }}:/liquibase" \
             -e GOOGLE_APPLICATION_CREDENTIALS=/liquibase/gcp-creds.json \
             --entrypoint=/bin/sh \
             ${{ env.LIQUIBASE_IMAGE }} \
-            -c "bash -x -c '/liquibase/liquibase --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} --log-level=debug update --contexts='\${APP_ENV}' && echo \$? > /liquibase/liquibase-status.txt'" \
+            -c "bash -x -c 'PATH=\$PATH:/liquibase:/usr/local/bin /liquibase/liquibase --defaultsFile=/liquibase/${{ env.LIQUIBASE_PROPERTIES }} --log-level=debug update --contexts='\${APP_ENV}' && echo \$? > /liquibase/liquibase-status.txt'" \
             APP_ENV="${{ env.APP_ENV }}" || { echo "Liquibase update failed"; exit 1; }
           cat "${{ github.workspace }}/liquibase-status.txt"
         shell: bash
